### PR TITLE
add a toggle for displaying compiled SQL

### PR DESCRIPTION
**Pull request by samredai**
### Summary

This adds a toggle for showing the compile result for the SQL for a given node. This toggle is only available for metric, dimension, or transform nodes. Source nodes don't have any SQL and cube nodes don't have an "uncompiled" version of SQL so the SQL that's shown is already compiled.

https://github.com/DataJunction/dj-ui/assets/43911210/689eba7a-cfdc-4125-9bd0-30c81756f0de

### Test Plan

Tested locally.

### Deployment Plan

N/A

### CODE REVIEW

**Review by shangyian — APPROVED** [review]
Nice! This looks useful. 

Btw at some point I started adding a SQL tab to nodes that lets users select dimensions and filters and view the compiled SQL. It's not quite complete yet as I haven't added the filters part, but I'll open the PR in case you want to build on that. 

Screenshot 2023-06-06 at 11 32 05 PM

**Comment by agorajek** [comment]
This is awesome. This view really shines the light on our alias generator though. I understand that it is easier to make them this way rather than from a sequence, but I think we should at some point convert these aliases to t1...tN os something similar. If nothing else I think they are making the SQL hard to read.

**Review by agorajek — APPROVED** [review]

**Comment by samredai** [comment]
@agorajek i think the challenge is that the aliases have to be deterministic since the table alias and the column references are built at different stages.

Maybe we can do something where we have an alias map that builds up as part of the CompileContext and is referenced every time a table alias or column name is set. So it could start with `{"default.foo": "t1"}` and then when it hits the next table alias it references that map and increments to "t2" for the next alias. @CircArgs that should work right?

**Comment by CircArgs** [comment]
@samredai once the sql is built you go do anything you wanted to aliases. So, you could swap all aliases `default_DOT_foo` with `t1` just by manipulating the ast

**Pull request merged**
